### ISSUE TITLE
ESP-12E footprint issues

### ISSUE THREAD

**Issue by varesa** [SashsLab/ESP8266#1]
The ESP8266 ESP-12-E footprint has all pins with the designator "1" and the 3D model upside down
Designators:
![esp12e_2d](https://cloud.githubusercontent.com/assets/833482/9566513/d860b85e-4f10-11e5-8daf-f0ff18a61cac.PNG)

3D model:
![esp12e_3d](https://cloud.githubusercontent.com/assets/833482/9566514/d86264ce-4f10-11e5-8a4a-54617423d239.PNG)

**Comment by SashsLab** [comment]
Varesa thanks!

**Comment by Humancell** [comment]
Is there a reason this issue is still open?  Or was is resolved?

**Comment by SashsLab** [comment]
It is fixed as veresa wrote.

**Comment by rechaugusto** [comment]
This 3D still ungly if compare with ESP-12 can some1 make it black and with Capsule like this? http://www.icstation.com/images/big/products/5593_8683.JPG THANKS for your work.
