### ISSUE TITLE
Fixed Reference to PCB Library

### ISSUE THREAD

**Issue by bkarl** [SashsLab/ESP8266#3]
Hello, thanks for your Effort and the great work!

When I tried to use the library I always got a "Footprint not found" error.
I found out that this happens due to a fixed reference path to the footprints library in the .schlib.
(See screenshot --> Location).

![wrongreference](https://cloud.githubusercontent.com/assets/2765716/10572126/a8e583e6-7645-11e5-9564-7a6c74199874.jpg)

When you change the path from "D:\tmp\github\ESP8266.PcbLib" to "ESP8266.PcbLib" everything works fine.

**Comment by TMaxElectronics** [comment]
Also fixed in PR #8
