### ISSUE TITLE
esp-07 

### ISSUE THREAD

**Issue by persian-michael-scott** [SashsLab/ESP8266#6]
it is not the esp-07 library esp-07 has 16 pins but this one in the library got 14 pins ...

**Comment by SashsLab** [comment]
In the days when the lib was crated the ESP-07 based on ESP8266 chipset was made the module had 14 pins.  New version has 16. check the link below the last image, you will noticed that pcb drawing has 14, image of the module has 16 (also pins are different).  Case closed.

https://www.geekbuying.com/item/ESP-07-ESP8266-Uart-Serial-To-Wifi-Wireless-Module-With-Built-in-Antenna-For-Arduino-Raspberry-Pi-343709.html
